#!/bin/sh

#troca favicon
find /usr/share/biglinux/kdebiglinux -type f -exec sed -i 's/big-favicon.*/xiva-favicon/' {} +
find /usr/share/plasma/plasmoids/org.biglinux.appsmenu/ -type f -exec sed -i 's/big-favicon-new/xiva-favicon/' {} +
#troca wallpaper
find /usr/share/biglinux/kdebiglinux -type f -exec sed -i 's/Image=\/usr\/share\/wallpapers\/.*/Image=\/usr\/share\/wallpapers\/xiva-wallpaper.png/' {} +
